exclude: ^db/init.sql$
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: trailing-whitespace

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.51.0
    hooks:
      - id: golangci-lint
        require_serial: true
